eureka:
  client:
    service-url:
      defaultZone: http://mchaha:mcha123@localhost:9010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期