server:
  port: 9020
spring:
  application:
    name: ly-env-gateway-server
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
  rabbitmq:
    host: localhost
    password: guest
    port: 5672
    username: guest
    virtual-host: /
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
eureka:
  client:
    service-url:
      defaultZone: http://mchaha:mcha123@localhost:9010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
zuul:
  prefix: /api
  routes:
    ly-env-gateway-server:
      path: /gateway/** # 以/api/gateway/**开头的请求，全部由网关服务处理
      strip-prefix: false # 不截断/gateway
leyou:
  gateway:
    configValue: Hello World!
    filter:
      allowPaths:
        - /api/gateway/allowPath
      forbidPaths:
        - /api/gateway/forbidPath