server:
  port: 9025
spring:
  application:
    name: ly-server-user-provider
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leyou_user?useUnicode=true&characterEncoding=UTF8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: devuser
    password: 123456
  redis:
    host: 192.168.124.99

  cloud:
    bus:
      trace:
        enabled: true
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
eureka:
  client:
    service-url:
      defaultZone: http://mchaha:mcha123@localhost:9010/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期