server:
  port: 9030
spring:
  application:
    name: ly-server-sms
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  rabbitmq:
    host: 192.168.124.99
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
leyou:
  sms:
    accessKeyId: ""
    accessKeySecret: ""
    signName: ""
    templateCode: ""