server:
  port: 9030
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  application:
    name: ly-server-sms
leyou:
  sms:
    accessKeyId: ""
    accessKeySecret: ""
    signName: ""
    templateCode: ""