# Eureka客户端配置
eureka:
  client:
    # 配置与Eureka Server交互的地址，客户端的查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://mchaha:mcha123@localhost:9010/eureka/
  instance:
    # 租约续订时间间隔，以秒为单位，这里是5秒。默认是30秒
    lease-renewal-interval-in-seconds: 5
    # 租约到期持续时间，以秒为单位，这里是10秒。默认是90秒
    lease-expiration-duration-in-seconds: 10