# 应用端口号
server:
  port: 9020

#spring配置
spring:
  application:
    # 应用名称
    name: xyz-env-gateway-server

  # 数据库配置
  # redis配置
  redis:
    host: 192.168.124.99
    port: 6379
    
  # spring-cloud配置
  cloud:
    bus:
      # 应用程序实例的标识id
      id: ${spring.application.name}:${server.port}
      # 启用消息总线，默认为true：启用
      enabled: true
      trace:
        # 开启消息追踪，默认false：关闭
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false

  # rabbitmq配置
  rabbitmq:
    # rabbitmq主机ip
    host: 192.168.124.99
    # rabbitmq应用端口
    port: 5672
    # 用户名
    username: guest
    # 密码
    password: guest
    virtual-host: /

  # sleuth + zipkin配置
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    # zipkin服务器的地址
    base-url: http://192.168.124.99:9411/

# 网关配置
zuul:
  sensitive-headers:
  # 路由前缀
  prefix: /api
  routes:
    xyz-env-gateway-server: 
      path: /gateway/** # 以/api/gateway/**开头的请求，全部由网关微服务处理
      strip-prefix: false
    xyz-server-user-provider: 
      path: /user/**
      strip-prefix: false
    xyz-server-user-provider: 
      path: /role/**
      strip-prefix: false
    xyz-server-user-provider: 
      path: /menu/**
      strip-prefix: false
    xyz-server-auth-provider:
      path: /auth/**
      strip-prefix: false
  host:
    max-per-route-connections: 60000
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000

# 其它参数配置
xyz:
  gateway:
    filter:
      path:
        allowPaths:
          - /api/gateway/allowPath
          - /api/auth/accredit
          - /api/auth/verify
          - /api/auth/logout
        forbidPaths:
          - /api/gateway/forbidPath
  jwt:
    token-header: Authorization
    secret: fenge-xyz
    pubKeyPath: D:/git/rsa/xyz-rsa/rsa.pub
    priKeyPath: D:/git/rsa/xyz-rsa/rsa.pri
    expire: 30 #单位分钟